// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvoZlRWC8WOwFrjO9N9d5C9FidmZestg8',
    appId: '1:185777210158:web:ed0fdacc0acb15c6fa70bf',
    messagingSenderId: '185777210158',
    projectId: 'personalyze-ed347',
    authDomain: 'personalyze-ed347.firebaseapp.com',
    storageBucket: 'personalyze-ed347.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyXHDIV8SURcK3-QQINRF72Rc6x_QJZuw',
    appId: '1:185777210158:android:c4f45bb1755e30b0fa70bf',
    messagingSenderId: '185777210158',
    projectId: 'personalyze-ed347',
    storageBucket: 'personalyze-ed347.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClzBjUbtYEG83rIzQxr1VzNkIwDUNCqaw',
    appId: '1:185777210158:ios:456e4136bfc38418fa70bf',
    messagingSenderId: '185777210158',
    projectId: 'personalyze-ed347',
    storageBucket: 'personalyze-ed347.firebasestorage.app',
    iosBundleId: 'com.example.personlayze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClzBjUbtYEG83rIzQxr1VzNkIwDUNCqaw',
    appId: '1:185777210158:ios:456e4136bfc38418fa70bf',
    messagingSenderId: '185777210158',
    projectId: 'personalyze-ed347',
    storageBucket: 'personalyze-ed347.firebasestorage.app',
    iosBundleId: 'com.example.personlayze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvoZlRWC8WOwFrjO9N9d5C9FidmZestg8',
    appId: '1:185777210158:web:f25783f3fad4a50afa70bf',
    messagingSenderId: '185777210158',
    projectId: 'personalyze-ed347',
    authDomain: 'personalyze-ed347.firebaseapp.com',
    storageBucket: 'personalyze-ed347.firebasestorage.app',
  );
}
